# Site settings
title: Charlie Oh
email: 
description: > Polar Bears + Magic ~= Charlie?
baseurl: ""
url: "http://taxdouble.github.io"
twitter_username: username
github_username: username

# Build settings
markdown: redcarpet
markdown_ext:  markdown,mkdown,mkdn,mkd,md

redcarpet:
  extensions: ["tables", "autolink", "strikethrough", "space_after_headers", "fenced_code_blocks"]
